name: build and test

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  run:
    name: build
    strategy:
      fail-fast: true
      matrix:
        os:
            - macos-latest
            - ubuntu-latest
            - windows-latest
        ocaml-compiler:
            - '4.03.0'
            - '4.13.1'

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: dra27/setup-ocaml@safe-git-v1
        with:
          ocaml-version: ${{ matrix.ocaml-compiler }}

      - run: opam pin -n .

      - run: opam depext -yt containers containers-data containers-thread

      - run: opam install -t containers containers-data containers-thread --deps-only
        if: matrix.os == 'ubuntu-latest'

      - run: |
          opam install -t containers --deps-only ;
          opam install containers-data containers-thread --deps-only  # no test deps
        if: matrix.os != 'ubuntu-latest'

      - run: opam exec -- dune build '@install'

      - run: opam exec -- dune runtest
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - run: opam exec -- dune runtest -j 1 -p containers # test only core on non-ubuntu platform
        if: ${{ matrix.os != 'ubuntu-latest' }}

